# Generated by Django 3.1.7 on 2021-03-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_clientinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='portfolio')),
            ],
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='link',
            field=models.CharField(max_length=400),
        ),
    ]
